name: Node.js CI/CD

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    - run: |
        touch .env
        echo "${{secrets.PROD_ENV_FILE}}" > .env

    - run: pm2 restart server
    
    # Uncomment if you need to run the build step
    # - run: |
    #     npm run build --if-present
    #     npm run serve
