name: Node.js CI/CD

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run start --if-present
    - run: | 
        touch .env
        echo "${{secrets.PROD_ENV_FILE}}" > .env
